#
# CSE186 Assignment 7
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 7
  version: 0.1.0
  title: CSE186 Assignment 7

servers:
  - url: http://localhost:3010

paths:
  /v0/mail:
    get:
      description: Returns all EMail
      parameters:
        - in: query
          name: mailbox
          schema:
            type: string
          required: false
        - in: query
          name: from
          schema:
            type: string
          required: false
      responses:
        200:
          description: Emails in mailbox
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailNoContent'
        404:
          description: No emails found

    post:
      description: saves a new email into sent mailbox
      requestBody:
        description: Application to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        200:
          description: Worked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostOutput'
        400:
          description: submitted e-mail has unexpected properties

  /v0/mail/{id}:
    get:
      description: Get email by id
      parameters:
        - name: id
          in: path
          description: find email of given id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: email found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailWithContent'
        404:
          description: email not found

    put:
      description: move email of selected id to the named mailbox
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: mailbox
        required: true
        schema:
          type: string
      responses:
        204:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Emailput'
        404:
          description: id does not identify a known e-mail
        409:
          description: Named mailbox is "Sent" and mail identified by id is not already in the sent mailbox


components:
  schemas:

    EmailWithContent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        subject:
          type: string
        received:
          type: string
        from:
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        content:
          type: string
      required:
        - id
        - to
        - from
        - subject
        - received
        - content


    EmailNoContent:
      type: array
      properties:
        name:
          type: string
        mail:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              to:
                properties:
                  name:
                    type: string
                  email:
                    type: string
                    format: email
              from:
                properties:
                  name:
                    type: string
                  email:
                    type: string
                    format: email
              sent:
                type: string
                format: date-time
              subject:
                type: string
              received:
                type: string
                format: date-time
            additionalProperties: false
          required:
            - id
            - to
            - from
            - sent
            - subject
            - received
      required:
        - name
        - mail
      additionalProperties: false


    Emailput:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        from:
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        subject:
          type: string
        sent:
          type: string
          format: date-time
        received:
          type: string
          format: date-time
        content:
          type: string

      required:
        - id
        - content
        - to
        - subject
        - sent
        - received
        - from


    Email:
      type: object
      properties:
        subject:
          type: string
        content:
          type: string
        to:
          properties:
            name:
              type: string
            email:
              type: string
              format: email
          required:
            - name
            - email
          additionalProperties: false
      required:
       - subject
       - content
       - to
      additionalProperties: false
      
    PostOutput:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        from:
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        sent:
          type: string
          format: date-time
        received:
          type: string
          format: date-time
        subject:
          type: string
        content:
          type: string
      required:
        - id
        - from
        - to
        - received
        - sent
        - subject
        - content

    # getInboxType:
    #   type: array
    #   items:
    #     $ref: '#/components/schemas/EmailNoContent'
