#
# CSE186 Assignment 6
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 6
  version: 0.1.0
  title: CSE186 Assignment 6

servers:
  - url: http://localhost:3010

paths:
  /v0/mail:
    get:
      description: Return all the emails in the system as an array of named mailboxes containing arrays of e-mails, one per mailbox.
      parameters:
        - in: query
          name: mailbox
          schema:
            type: string
          required: false
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getInboxType'
        404:
          description: Not Found

# POST /v0/mail
  # Save a new email sent in the HTTP request body into the sent mailbox and return the newly created e-mail. 
  # The id, received, from-name and from-email properties should be missing on submission and set on return; 
  # id should be set to a valid UUID, received should be set to the current date and time, 
    # from-email and from-name should be as for all existing emails in the sent mailbox. 
  # Throw a 400 error if the submitted e-mail has any unexpected properties.
    post:
      description: saves a new email into sent mailbox
      requestBody:
        description: Application to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        200:
          description: Worked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostOutput'
        400:
          description: submitted e-mail has unexpected properties

  /v0/mail/{id}:
    get:
      description: Get email by id
      parameters:
        - name: id
          in: path
          description: find email of given id
          required: true
          schema:
            type: string
            format: uuid

      responses:
        200:
          description: email found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailWithContent'
        404:
          description: email not found

    put:
        description: move email of selected id to the named mailbox
        parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: mailbox
          required: true
          schema:
            type: string

        responses:
          204:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/EmailMove'
          404:
            description: id does not identify a known e-mail
          409:
            description: Named mailbox is "Sent" and mail identified by id is not already in the sent mailbox

components:
  schemas:

    EmailMove:
      type: object
      properties:
        id:
          type: string
          # format: uuid
        content:
          type: string
        to-name:
          type: string
        to-email:
          type: string
          format: email
        subject:
          type: string
        received:
          type: string

        from-name:
          type: string
        from-email:
          type: string
          format: email
      required:
        - id
        - content
        - to-name
        - to-email
        - subject
        - received
        - from-name
        - from-email

    Email:
      type: object
      properties:
        subject:
          type: string
        content:
          type: string
        to-name:
          type: string
        to-email:
          type: string
          format: email
      required:
       - subject
       - content
       - to-name
       - to-email
      additionalProperties: false
      
    PostOutput:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to-name:
          type: string
        to-email:
          type: string
          format: email
        # content:
          # type: string
        subject:
          type: string
        received:
          type: string
          format: date-time
        from-name:
          type: string
        from-email:
          type: string
          format: email
      required:
        - id
        - to-name
        - to-email
        - subject
        - received
        - from-name
        - from-email
        - content
        

    getInboxType:
      type: array
      items:
        $ref: '#/components/schemas/EmailNoContent'

    EmailWithContent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to-name:
          type: string
        to-email:
          type: string
          format: email
        subject:
          type: string
        received:
          type: string
        from-name:
          type: string
        from-email:
          type: string
          format: email
        content:
          type: string
      required:
        - id
        - to-name
        - to-email
        - subject
        - received
        - from-name
        - from-email
        - content

    EmailNoContent:
      type: object
      properties:
        name:
          type: string
        mail:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              to-name:
                type: string
              to-email:
                type: string
                format: email
              subject:
                type: string
              received:
                type: string
              from-name:
                type: string
              from-email:
                type: string
                format: email
            additionalProperties: false
          required:
            - id
            - to-name
            - to-email
            - subject
            - received
            - from-name
            - from-email
      required:
        - name
        - mail
      additionalProperties: false